### PR TITLE
Changed ImageUploadField to UploadField

### PR DESCRIPTION
**Pull request by martinduparc**
ImageUploadField is not a valid field anymore

### CODE REVIEW

**Comment by martinduparc** [comment]
I am still seeing the ImageUploadField
https://github.com/lekoala/silverstripe-mandrill/blob/master/code/extensions/MandrillSiteConfig.php#L38

The field has been deprecated and UploadField should be used instead.

**Comment by lekoala** [comment]
Indeed, I have some troubles pushing to github at the moment...

Actually, the field is from another of my modules
https://github.com/lekoala/silverstripe-form-extras

I don't think the class ImageUploadField exists in the main framework (although I remember that back in SS 2 days, there was something like that indeed).

I'll push the changes as soon as possibles.

**Comment by martinduparc** [comment]
You're right, it used to exist in previous versions of SilverStripe. They made a general upload field I guess.

Thanks for your work on the library!

**Comment by lekoala** [comment]
ok it's pushed now. I've also added my form-extras module as a suggested module

**Pull request closed without merging**
